const BAD_REQUEST_CODE = 400;
const NOT_FOUND_CODE = 404;
const INTERNAL_SERVICE_ERROR_CODE = 500;
const UNAUTHORIZED_CODE = 401;
const FORBIDDEN_CODE = 403;
const CONFLICT_CODE = 409;

module.exports = {
  BAD_REQUEST_CODE,
  NOT_FOUND_CODE,
  INTERNAL_SERVICE_ERROR_CODE,
  UNAUTHORIZED_CODE,
  FORBIDDEN_CODE,
  CONFLICT_CODE,
};
